### ISSUE TITLE
SetOverlayNotificationPosition

### ISSUE THREAD

**Issue by subsoap** [britzl/steamworks-defold#12]
This doesn't seem to be working?

https://partner.steamgames.com/doc/api/ISteamUtils#SetOverlayNotificationPosition

Maybe I'm trying to use it wrong?

```
steamworks.utils_set_overlay_notification_position(0)
attempt to call field 'utils_set_overlay_notification_position' (a nil value)
stack traceback:
```

**Comment by britzl** [comment]
The Overlay functions are all excluded. I wasn't able to get it to work. See comment here: https://github.com/britzl/steamworks-defold/issues/10

It does however mention in the docs "While in development and running your game" like there should be a difference between how the Overlay behaves while developing a game and while having it launched form Steam. Perhaps you can give it a try?

**Comment by subsoap** [comment]
![2019-09-13 05_21_03-Slack _ jcash _ Defold Hangout](https://user-images.githubusercontent.com/409170/64862018-595d6c80-d5e6-11e9-967e-d8d231c888f1.png)

Think something like this could work?

**Comment by britzl** [comment]
Ah, yes, that would be worth trying!

**Comment by subsoap** [comment]
This works now

```
function init(self)
	local status, error = pcall(steamworks.init)
	if not status then print("Error: " .. error) return end

	steamworks.set_listener(function(self, e, t)
		print(e)
		pprint(t)
	end)
		
	steamworks.utils_set_overlay_notification_position(2)
end
``` 

```
steamworks.POSITION_TOP_LEFT 0
steamworks.POSITION_TOP_RIGHT 1
steamworks.POSITION_BOTTOM_LEFT 2
steamworks.POSITION_BOTTOM_RIGHT 3
```
