### ISSUE TITLE
Workshop support?

### ISSUE THREAD

**Issue by CGNick** [britzl/steamworks-defold#13]
Is there any chance you're willing to add the UGC API to allow for steam workshop mods?

**Comment by britzl** [comment]
Hi! Would you mind trying this branch and let me know if it works for you?

https://github.com/britzl/steamworks-defold/tree/ugc

**Comment by CGNick** [comment]
Dang! You work fast, I wasn't expecting you'd add it so quickly. I'm a bit away from my testing environment at the moment, but the moment I try it, I'll let you know. Thanks for the update btw.

**Comment by subsoap** [comment]
@britzl is the most professional and efficient developer I know of!

**Comment by britzl** [comment]
@CGNick well, in all honesty, the Steamworks extension is generated from an API specification so the changes required were fairly small. I had to manually add handling of a SteamParamStringArray_t struct used by SetItemTags, but other than that it is all generated code.

**Comment by CGNick** [comment]
Either way, I do appreciate the quick response. I'll be sure to let you know if it works properly, when I get around to having a chance to test it

**Comment by britzl** [comment]
Merged into master.
