### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by dapetcu21** [britzl/steamworks-defold#17]
@britzl Can you please make a new release of this that includes my #16 PR?

I think asvegren [here](https://forum.defold.com/t/steamworks-native-extension/29445) read the README on Github (which is master and doesn't have the lib copying step), but used the 1.4.0 zip, which still requires copying the libs manually.

**Comment by britzl** [comment]
https://github.com/britzl/steamworks-defold/releases/tag/1.4.1
