### ISSUE TITLE
Project is not launching from Defold editor after integrating  steamworks

### ISSUE THREAD

**Issue by Sublustris** [britzl/steamworks-defold#24]
Defold 1.3.2, Steamworks 2.0.3, Windows.
When trying to build project  from editor (CTRL+B) ide displays `Launched Local dmengine.exe` on the editor bottom bar, without any errors on the console. Nothing more happens.

Then, when I'm launching the .bat script provided with library, it shows the following:

![изображение](https://user-images.githubusercontent.com/43444545/171129757-1b54e79c-6be7-4936-b0da-1bdbcb882f7a.png)

all res are on their places. ((
![изображение](https://user-images.githubusercontent.com/43444545/171130522-d0fba429-c673-4f39-aa58-7078ced2fa11.png)

![изображение](https://user-images.githubusercontent.com/43444545/171130588-0e8783ae-3d76-40e2-9dd5-c618304232c7.png)

After removing  steamworks from project all becomes ok (((

**Comment by britzl** [comment]
Closed via #25
