### ISSUE TITLE
ERROR:SCRIPT: Steam is not running

### ISSUE THREAD

**Issue by subsoap** [britzl/steamworks-defold#6]
I feel like this should not make a script error out. Because otherwise I need to pcall it.

**Comment by subsoap** [comment]
Something I foresee is Steam being closed while a game is running for example. Devs may include Steamworks functions in their main script which would break their main loop if they didn't pcall wrap the Steamworks functions.

**Comment by subsoap** [comment]
I just tested this and games automatically close when Steam closes if they are using the Steamworks extension!? 😬Not good!

Edit: maybe that's something Steam does now.

**Comment by britzl** [comment]
When I shut down steam while the example is running I get a popup saying "Waiting for Spacewar to shut down". The game doesn't shut down though. I wonder if there's a callback in the API that the game should react to and gracefully shut down or in some other way handle that the Steam app is shut down?
