### ISSUE TITLE
Move bundle files to res folder of extension?

### ISSUE THREAD

**Issue by subsoap** [britzl/steamworks-defold#9]
Users will still need to manually place dlls etc. next to their game.project to run from editor

**Comment by britzl** [comment]
I'm not sure I understand. What do you mean that we should change?

**Comment by subsoap** [comment]
![2019-02-23 13_37_31-window](https://user-images.githubusercontent.com/409170/53291966-5137ff80-3770-11e9-845d-29201c3352b5.png)

What I mean is the bundle folder is custom. These files should be in the res folder. Then they will automatically be copied next to the exe etc. without needing to be included inside of a project directly. Although it still seems that files in the res folder of an extension are still not setup properly so that they work with building from the editor.

**Comment by britzl** [comment]
Ah, I see. I actually forgot about the possibility of providing a res folder.

**Comment by britzl** [comment]
And as you said, it doesn't seem to work when building from within the editor. Only when bundling.

**Comment by subsoap** [comment]
@jcash did mention that it doesn't work... yet. Either with or without res folder user still has to manually (or with a script) copy files for now. What I do is just put the Windows dlls in the folder with the game.project and it works while testing in the editor.
